src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email='';

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password='';

    /**
     * @ORM\OneToMany(targetEntity=Cart::class, mappedBy="user")
     */
    private $carts;

    public function __construct()
    {
        $this->carts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection<int, Cart>
     */
    public function getCarts(): Collection
    {
        return $this->carts;
    }

    public function addCart(Cart $cart): self
    {
        if (!$this->carts->contains($cart)) {
            $this->carts[] = $cart;
            $cart->setUser($this);
        }

        return $this;
    }

    public function removeCart(Cart $cart): self
    {
        if ($this->carts->removeElement($cart)) {
            // set the owning side to null (unless already changed)
            if ($cart->getUser() === $this) {
                $cart->setUser(null);
            }
        }

        return $this;
    }
}

templates/parts/footer.html.twig
{% block body %}
    <div class="container-fluid mt-5 pb-5 bg-dark text-light">
        <div class="row">
            <div class="col-3 ml-5">
                <br/>
                <div>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Cum putem cumunica:</div>
                <br/>
                <i class="fa fa-envelope-o fa-3x" aria-hidden="true"></i>&nbsp; office@sneakersshop.ro
                <br/>
                <br/>
                <i class="fa fa-phone fa-3x" aria-hidden="true"></i>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 0723456789
                <br/>
            </div>
            <div class="col-3 ml-5">
                <br/>
                <div>Informatii:</div>
                <br/>
                <div>Contact</div>
                <br/>
                <div>Politica de confidentialitate</div>
                <br/>
                <div>Termeni si Conditii</div>
                <br/>
            </div>
            <div class="col-3 ml-5">
                <br/>
                <div>Contul meu</div>
                <br/>
                <div>Autentificare</div>
                <br/>
                <div>Inregistrare</div>
                <br/>
                <div>Cos cumparaturi</div>
                <br/>
            </div>
            <div class="col-2 ml-2">
                <br/>
                <div>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp;Alaturati-ne</div>
                <br/>
                <div>&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <i class="fa fa-facebook-official fa-3x" aria-hidden="true"></i></div>
                <br/>
                <div>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <i class="fa fa-instagram fa-3x" aria-hidden="true"></i></div>
                <br/>
                <div>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; <i class="fa fa-youtube-play fa-3x" aria-hidden="true"></i></div>
                <br/>
            </div>
        </div>
    </div>
{% endblock %}

templates/parts/header.html.twig
{% block body %}
    <div class="container-fluid bg-info mb-2">
        <div class="row">
            <div class="col-12">
                <div class="container">
                    <div class="row">
                        <div class="col-6">
                            <a class="navbar-brand" href="{{ url('homepage') }}">
                                <img width="200px" src="{{ asset('images/logo_shop.jpg') }}" alt="logo.png">
                            </a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 bg-info pb-1">
                            <nav class="navbar navbar-expand-lg navbar-light p-0 mb-1">
                                <nav class="collapse navbar-collapse" id="navbarSupportedContent">
                                    <ul class="navbar-nav">
                                        <li class="nav-item dropdown">
                                            <div class="dropdown mr-1">
                                                <button class="btn dropdown-toggle" type="button"
                                                        id="dropdownMenuButton" data-toggle="dropdown"
                                                        aria-haspopup="true"
                                                        aria-expanded="false">
                                                    CATEGORIE
                                                </button>
                                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                                    {% for category in categories %}
                                                        <a class="dropdown-item"
                                                           href="{{ url('category', {'category':category.id}) }}">
                                                            {{ category.name }}
                                                        </a>
                                                    {% endfor %}
                                                </div>
                                            </div>
                                        </li>
                                        <li>
                                            <a class="btn btn-light mr-1" href="{{ url('homepage') }}" role="button">Home <i class="fa fa-home" aria-hidden="true"></i></a>
                                        </li>
                                        <li>
                                            <a class="btn btn-light mr-1" href="{{ url('contact') }}" role="button">Contact <i class="fa fa-envelope" aria-hidden="true"></i></a>
                                        </li>
                                    </ul>
                                </nav>
                                        <nav class="navbar navbar-expand-lg ml-auto align-content-end p-0">
                                            <ul class="navbar-nav">
                                                <li>
                                                    <a class="btn btn-light mr-1" href="{{ url('cart') }}" role="button">Cosul meu <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                                        {% if cartService.getCartCount() > 0 %}
                                                            <span class="badge badge-danger">{{ cartService.getCartCount() }}</span>
                                                        {% endif %}
                                                    </a>
                                                </li>
                                                <li class="nav-item ">
                                                    {% if app.user %}
                                                    <button class="btn btn-light">Esti logat ca {{ app.user.username }}, <a href="{{ path('app_logout') }}">Logout</a></button>
                                                </li>
                                                {% else %}
                                                    <li class="nav-item">
                                                        <a class="btn btn-light" href="{{ url('app_login') }}" role="button">Login <i class="fa fa-sign-in" aria-hidden="true"></i></a>
                                                    </li>
                                                {% endif %}
                                            </ul>
                                        </nav>
                                </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <img class="align-content-center" width="550px" height="150px" src="{{ asset('images/10off.jpg') }}" alt="10off.jpg"/><img width="550px" height="150px" src="{{ asset('images/10off.jpg') }}" alt="10off.jpg"/>
    </div>
    <div class="container text-center mb-2 pr-0 pl-4">
    <style>
        p {
            text-align: center;
            font-size: 60px;
            background-color: lightseagreen;
            margin-top: 0px;
        }
    </style>
        <p id="demo">SALES END IN </p>
        <script>
            var countDownDate = new Date("Mar 31, 2023 23:59:59").getTime();
            var x = setInterval(function() {
                var now = new Date().getTime();
                var distance = countDownDate - now;
                var days = Math.floor(distance / (1000 * 60 * 60 * 24));
                var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
                var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
                var seconds = Math.floor((distance % (1000 * 60)) / 1000);
                document.getElementById("demo").innerHTML = "SALES END IN -> " + days + "d " + hours + "h "
                    + minutes + "m " + seconds + "s " ;
                if (distance < 0) {
                    clearInterval(x);
                    document.getElementById("demo").innerHTML = "EXPIRED";
                }
            }, 1000);
        </script>
    </div>
{% endblock %}